"use client"
import { Geist, Geist_Mono } from "next/font/google";
import ThemeProvider from "../lib/Themecontext.js";
import "./globals.css";
import InnerLayout from "./InnerLayout.js";
import { Provider } from "react-redux";
import store from "../store/store.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Chatty",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>

          <ThemeProvider>
            <InnerLayout>{children}</InnerLayout>
          </ThemeProvider>

        </Provider>

      </body>
    </html>
  );
}
